### PR TITLE
new(cmd): add artifact config command

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area library

/area cli

/area tests

> /area examples

**What this PR does / why we need it**:

Add a new command for artifacts: `falcoctl artifact config` which fetches the config layer for a given artifact.

```bash
❯ falcoctl artifact config falco-rules | jq
{
  "name": "falco-rules",
  "version": "2.0.0",
  "requirements": [
    {
      "name": "engine_version",
      "version": "26"
    }
  ]
}
```

**Which issue(s) this PR fixes**:
#332 

Fixes #
#332 
**Special notes for your reviewer**:

### CODE REVIEW

**Comment by loresuso** [comment]
Pretty useful! I like it!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
