### PR TITLE
doc: issue and pull request template

### PR DESCRIPTION
**Pull request by fntlnz**
This PR adds issue and pull-request templates.

```release-note
NONE
```

### CODE REVIEW

**Comment by leodido** [comment]
We propose the attached issue and pull-request templates.

The areas are: library, cli, tests.

**Comment by rajibmitra** [comment]
@leodido  yes I agree , we need to create the labels manually.

**Comment by fntlnz** [comment]
OK we will create the labels then!

@rajibmitra @markyjackson-taulia until Marky's work on the new Prow is finished, here's teh tide status page for the projects. http://falco-eks-alb-1155263759.us-east-1.elb.amazonaws.com/tide

**Comment by fntlnz** [comment]
Ok all the labels are in place!

**Pull request merged**
