### PR TITLE
new(cmd/push): add progress bar while pushing artifacts

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

/kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area library

/area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

Add support for a tracker interface in the pusher and puller libraries. It allows to define a custom tracker that gives information about the ongoing pull and push operations.

Using the new tracker interface the `push` command shows the progress of the push operations using a progress bar:

```bash
❯ ./falcoctl registry push --type plugin cloudtrail-0.3.0-linux-x86_64.tar.gz  ghcr.io/alacuku/cloudtrail:latest
 INFO  Preparing to push artifact "cloudtrail-0.3.0-linux-x86_64.tar.gz" of type "plugin"
 INFO  Pushing 44136fa355b3: ############################################# 100% 
 INFO  Pushing 45a192b10e9b: ############################################# 100% 
 INFO  Pushing d1fbffa452f0: ############################################# 100% 
 INFO  Pushing d1f85fb4ec73: ############################################# 100% 
 INFO  Artifact pushed. Digest: "sha256:d1fbffa452f02c84c93b35d5b7f81665a652df3baa9bc3eaa7c5a22f4586054e"
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alacuku** [comment]
@leogr @FedeDP

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by leogr** [comment]
Hey @alacuku 

This PR has a conflict, could you rebase please? :pray: 

Otherwise, LGTM :)

**Comment by alacuku** [comment]
> Hey @alacuku
> 
> This PR has a conflict, could you rebase please? pray
> 
> Otherwise, LGTM :)

The PR has been rebased. After this one is merged I will rebase and squash the #147!

**Review by leogr — APPROVED** [review]

**Pull request merged**
