### PR TITLE
new(cmd/push): add progress bar while pulling artifacts

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area library

/area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

Using the new tracker interface (introduced in #146 ) the pull command shows the progress of the pull operations using a progress bar:
```bash
❯ ./falcoctl registry pull --type=rulesfile  ghcr.io/alacuku/myrules:latest --dest-dir=./destDir
 INFO  Preparing to pull artifact "ghcr.io/alacuku/myrules:latest" of type "rulesfile"
 INFO  Pulling artifact in "./destDir" directory
 INFO  Pulling 44136fa355b3: ############################################# 100% 
 INFO  Pulling ba4a8c11413e: ############################################# 100% 
 INFO  Pulling 3e0850ae8f9c: ############################################# 100% 
 INFO  Pulling 2cd1c59c6da5: ############################################# 100% 
 INFO  Artifact pulled. Digest: "sha256:2cd1c59c6da5a16720ee3c1c3efbce78abd10a313702f542bbd81eedf3ae75ce"
```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This PR is based on #146.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by leogr — APPROVED** [review]
:heart_eyes:

**Review by leogr — APPROVED** [review]

**Comment by alacuku** [comment]
The PR has been rebased on master, and it's ready to be merged!

**Review by leogr — APPROVED** [review]
Nice!

**Pull request merged**
