### PR TITLE
bugpatching issue 344 vulnerabilities including GHSA-m425-mq94-257g

### LINKED ISSUE #344: patching go vulnerability GHSA-m425-mq94-257g
**What would you like to be added**: I am suggesting we update alpine 3.18.3 to 3.18.4 and add a line to update libssl3 and libcrypto3 in order to patch some vulns for that as well 

**Why is this needed**: to patch go vulnerabilities and some libssl and openssl type stuff

### PR DESCRIPTION
**Pull request by cschp**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug 

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area library

> /area cli

> /area tests

> /area examples

**What this PR does / why we need it**: upgrades alpine in dockerfile from 3.18.3 to 3.18.4 to patch a go vulnerability then upgrades and patches libssl3 and libcrypto3

**Which issue(s) this PR fixes**:344

Fixes #344 

**Special notes for your reviewer**: please let me know if i messed up formatting somewhere as this is my first pr here

### CODE REVIEW

**Comment by leogr** [comment]
@LucaGuerra PTAL

**Comment by LucaGuerra** [comment]
@leogr LGTM!

**Comment by cschp** [comment]
@leogr @LucaGuerra who do i need lgtm from to merge?

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
