### PR TITLE
[wip] Fix search registry

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area library

/area cli

> /area tests

> /area examples

**What this PR does / why we need it**:
This PR reflects the changes to the plugin registry in order to let the command `search registry` work again. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — COMMENTED** [review]
Hey! Just jumping in to say that I don't think this approach of duplicating the registry definitions across multiple repositories will scale well in the future.

I opened a PR in `falcosecurity/plugins` to make part of the registry tool code importable in projects like this: https://github.com/falcosecurity/plugins/pull/120

**Comment by loresuso** [comment]
Hi @jasondellaluce! Totally agree, I was thinking to do the same. I am going to modify this PR soon, putting it on wip for the moment, thank you!

**Comment by jasondellaluce** [comment]
@loresuso just letting you known that https://github.com/falcosecurity/plugins/pull/120 got merged, and you should now be able to import the code you need as `github.com/falcosecurity/plugins/build/registry/pkg/registry`.

**Comment by loresuso** [comment]
The search command will be completely reimplemented with a new approach. Closing.

**Pull request closed without merging**
