### PR TITLE
Bug #114 Fixed -- > Country and Config have same shorthand

### PR DESCRIPTION
**Pull request by atharva29**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area library

> /area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by atharva29** [comment]
Fixed #114

**Comment by leogr** [comment]
Hey @atharva29 

Thank you for this PR! :star_struck: 

Could you [sign off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) your commit, please? Our policy requires it :pray: 

Otherwise SGTM.

**Comment by xi2817-aajgaonkar** [comment]
Signed-off-by: Atharva Ajgaonkar atharvaajgaonkar29@gmail.com

**Comment by atharva29** [comment]
> Signed-off-by: Atharva Ajgaonkar [atharvaajgaonkar29@gmail.com](mailto:atharvaajgaonkar29@gmail.com)

ignore this

**Review by leogr — APPROVED** [review]
Thank you!

**Pull request merged**
