### PR TITLE
docs(README.md): added artifact follow documentation

### PR DESCRIPTION
**Pull request by therealbobo**
Signed-off-by: Roberto Scolaro <roberto.scolaro21@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area library

> /area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

The documentation for the `falcoctl artifact follow` command was missing.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
NONE

### CODE REVIEW

**Review by alacuku — APPROVED** [review]
Nice job, thank you!

**Review by leogr — DISMISSED** [review]

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
