### PR TITLE
vote: docs(OWNERS): add alacuku (Aldo Lacuku) to approvers

### PR DESCRIPTION
**Pull request by alacuku**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

 /kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area library

> /area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

Proposing myself as falcoctl maintainer as per 2024-03-27 community call discussion. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/hold until a week has passed or the majority is reached (as per our governance)

### CODE REVIEW

**Comment by alacuku** [comment]
@falcosecurity/falcoctl-maintainers

**Comment by FedeDP** [comment]
YES :ok: :rocket: :guitar: :1st_place_medal:

**Comment by leogr** [comment]
:heart_eyes: 

big +1 from me!!! :clap:

**Comment by cpanato** [comment]
+1

**Comment by leogr** [comment]
Welcome onboard :) 
/unhold

**Review by leogr — APPROVED** [review]

**Pull request merged**
