### PR TITLE
Create README.md for `gh-pages`

### PR DESCRIPTION
**Pull request by leogr**
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

> /kind flaky-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area library

> /area cli

> /area tests

> /area examples

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by FedeDP — APPROVED** [review]
/approve

**Review by zuc — APPROVED** [review]

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Ok, I guess @poiana is not well configured, since it's not applying the `approved` label. I'll manually merge this PR, and later double-check the config.

Screenshot from 2022-09-20 19-21-27

**Pull request merged**
