### PR TITLE
Update go to 1.20 and cleanup ci job

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind cleanup
/kind feature

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

- upgrade to use go1.20
- cleanup ci, adjust indentation, fix version comments and update hashes

**Which issue(s) this PR fixes**:

Fixes https://github.com/falcosecurity/falcoctl/issues/269

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
/assign @leogr 

working in another PR to have the signatures

**Comment by maxgio92** [comment]
Thanks @cpanato!

**Comment by maxgio92** [comment]
Just created #269 issue for this @cpanato if you want to link to it :)

**Review by alacuku — APPROVED** [review]
/LGTM

**Review by leogr — APPROVED** [review]

**Pull request merged**
